name: example-command
on:
  repository_dispatch:
    types: [example-command]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ruby
        run: ruby ./test.rb
