name: Comvent - Run if comment matches the keyword
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/comvent@v0.1.0 # This line would pull down the release version of comvent
        id: comvent # Add an ID, so that you can control your step later
        with:
          keyword: Trigger # This is the regex string to search in the comment

      - name: Run when comvent matches
        run: ruby ./test.rb
        # This checks whether comvent found a match
        if: steps.comvent.outputs.comvent != ''
        # Comvent returns the following values
        #   if found -> "found"
        #   if not   -> ""
